import telebot
import random

TOKEN = "enter your token here"  # Replace with your bot token
bot = telebot.TeleBot(TOKEN)

cs_quotes = [
"“Programs must be written for people to read, and only incidentally for 🔍 machines to execute.” – Harold Abelson",
    "“Programs must be written for people to 👨‍💻 read, and only incidentally for machines to execute.” – Harold Abelson",
    "“The function of good software is to make the complex appear 💻 simple.” – Grady Booch",
    "“Talk is cheap. Show me the code.” – ✨ Linus Torvalds",
    "“Software is a great combination of artistry and engineering.” – 🔍 Bill Gates",
    "“Programs must be written for people to 📘 read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Talk is 🔥 cheap. Show me the code.” – Linus Torvalds",
    "“Talk is cheap. Show me the code.” – ✨ Linus Torvalds",
    "“Talk is cheap. Show me 🚀 the code.” – Linus Torvalds",
    "“First, solve the problem. Then, 🔍 write the code.” – John Johnson",
    "“First, solve the problem. 🔍 Then, write the code.” – John Johnson",
    "“Software is a great combination of artistry and 👩‍💻 engineering.” – Bill Gates",
    "“Software is a great combination of artistry and engineering.” – 🖥️ Bill Gates",
    "“Any fool can write code that a computer can 🔥 understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 💻 John Johnson",
    "“Software is a great combination of artistry and engineering.” – 🖥️ Bill Gates",
    "“Software is a great combination of 📘 artistry and engineering.” – Bill Gates",
    "“Programs must be written for people to read, and only incidentally 🔧 for machines to execute.” – Harold Abelson",
    "“Simplicity is the soul of 👨‍💻 efficiency.” – Austin Freeman",
    "“The function of good software 👩‍💻 is to make the complex appear simple.” – Grady Booch",
    "“Talk is cheap. Show me the 🚀 code.” – Linus Torvalds",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 🔧 Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 🖥️ John Johnson",
    "“The function of good software is to make the complex ✨ appear simple.” – Grady Booch",
    "“First, solve the problem. 🧠 Then, write the code.” – John Johnson",
    "“Talk is cheap. Show me the code.” – 📘 Linus Torvalds",
    "“Software is a 🔍 great combination of artistry and engineering.” – Bill Gates",
    "“Talk is cheap. Show ✨ me the code.” – Linus Torvalds",
    "“Any fool can write ✨ code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“The function of good software is to make the complex 🤖 appear simple.” – Grady Booch",
    "“Any fool can write 🚀 code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Talk is cheap. Show me the 🖥️ code.” – Linus Torvalds",
    "“The function of good software is to make 🖥️ the complex appear simple.” – Grady Booch",
    "“Talk is 🚀 cheap. Show me the code.” – Linus Torvalds",
    "“First, solve the 🔍 problem. Then, write the code.” – John Johnson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 👨‍💻 Martin Fowler",
    "“First, solve the problem. ✨ Then, write the code.” – John Johnson",
    "“Simplicity is the soul of 👩‍💻 efficiency.” – Austin Freeman",
    "“Talk is 🔧 cheap. Show me the code.” – Linus Torvalds",
    "“Simplicity is the soul of efficiency.” – 🔥 Austin Freeman",
    "“Talk is cheap. Show me the code.” – 🔥 Linus Torvalds",
    "“Any fool can write code 🔥 that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Simplicity is the soul of 🔍 efficiency.” – Austin Freeman",
    "“Software is a great combination of 🚀 artistry and engineering.” – Bill Gates",
    "“The function of good software is to make the complex appear 🖥️ simple.” – Grady Booch",
    "“First, solve the problem. Then, write the ✨ code.” – John Johnson",
    "“Any fool can write code that a computer can understand. ✨ Good programmers write code that humans can understand.” – Martin Fowler",
    "“Software is a great combination of artistry and engineering.” – 🔍 Bill Gates",
    "“First, solve the problem. 📘 Then, write the code.” – John Johnson",
    "“Any fool can write code that a computer can ✨ understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Software is a great 📊 combination of artistry and engineering.” – Bill Gates",
    "“Any fool can write code that 🔍 a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Software is a great combination of artistry and engineering.” – 👩‍💻 Bill Gates",
    "“Talk is cheap. 🤖 Show me the code.” – Linus Torvalds",
    "“The function of good software is 🔥 to make the complex appear simple.” – Grady Booch",
    "“First, solve the 👩‍💻 problem. Then, write the code.” – John Johnson",
    "“Talk is cheap. Show me the ✨ code.” – Linus Torvalds",
    "“Programs must be written for people to 👨‍💻 read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Simplicity is the soul of 🔧 efficiency.” – Austin Freeman",
    "“Any fool can write code that a ✨ computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Talk is cheap. Show me the code.” – 👩‍💻 Linus Torvalds",
    "“First, solve 📊 the problem. Then, write the code.” – John Johnson",
    "“Talk is cheap. Show me the code.” – 💻 Linus Torvalds",
    "“Simplicity is the soul of efficiency.” – 🤖 Austin Freeman",
    "“Software is a great combination of artistry and ✨ engineering.” – Bill Gates",
    "“Simplicity is the soul of efficiency.” – 🚀 Austin Freeman",
    "“The function 👩‍💻 of good software is to make the complex appear simple.” – Grady Booch",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 🔥 Harold Abelson",
    "“The function of good software is to make the complex appear 🔍 simple.” – Grady Booch",
    "“Simplicity is the soul of 🧠 efficiency.” – Austin Freeman",
    "“First, solve the 💻 problem. Then, write the code.” – John Johnson",
    "“The function of good software is to make the complex 🖥️ appear simple.” – Grady Booch",
    "“Software is a great combination of 👨‍💻 artistry and engineering.” – Bill Gates",
    "“Any fool can write code that a computer can understand. Good programmers write 👨‍💻 code that humans can understand.” – Martin Fowler",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 👨‍💻 Harold Abelson",
    "“Any fool can write code that a computer can understand. Good programmers write code 🔍 that humans can understand.” – Martin Fowler",
    "“Any fool can 🚀 write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 🔥 John Johnson",
    "“Talk is cheap. Show me the code.” – 🔥 Linus Torvalds",
    "“First, solve the problem. Then, 🖥️ write the code.” – John Johnson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 🔍 Martin Fowler",
    "“Simplicity is the soul of 🚀 efficiency.” – Austin Freeman",
    "“Talk is cheap. Show me the ✨ code.” – Linus Torvalds",
    "“First, solve the 🔥 problem. Then, write the code.” – John Johnson",
    "“The function 🚀 of good software is to make the complex appear simple.” – Grady Booch",
    "“Programs must be written for people 🔥 to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“First, solve the problem. 👩‍💻 Then, write the code.” – John Johnson",
    "“Talk is cheap. Show me the code.” – 🤖 Linus Torvalds",
    "“Simplicity is the soul of efficiency.” – ✨ Austin Freeman",
    "“Any fool can write code that a 🧠 computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Simplicity is the soul of efficiency.” – 🤖 Austin Freeman",
    "“Programs must be written for people to read, and 👩‍💻 only incidentally for machines to execute.” – Harold Abelson",
    "“Talk is cheap. Show me 👩‍💻 the code.” – Linus Torvalds",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can 🖥️ understand.” – Martin Fowler",
    "“Simplicity is the soul of efficiency.” – 👩‍💻 Austin Freeman",
    "“Any fool can write code that a computer 👩‍💻 can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Simplicity is the soul of efficiency.” – ✨ Austin Freeman",
    "“Talk is cheap. Show me the code.” – 👨‍💻 Linus Torvalds",
    "“Simplicity is the soul of 🖥️ efficiency.” – Austin Freeman",
    "“Simplicity is the soul of 🤖 efficiency.” – Austin Freeman",
    "“Software is a great combination of artistry and engineering.” – 👨‍💻 Bill Gates",
    "“First, solve the problem. Then, write the code.” – 🔍 John Johnson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 🔥 Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 🔧 John Johnson",
    "“Talk is cheap. 🖥️ Show me the code.” – Linus Torvalds",
    "“Any fool can write code 🔍 that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“The function of good software is to make the complex appear 🔧 simple.” – Grady Booch",
    "“Simplicity is the soul of efficiency.” – 📘 Austin Freeman",
    "“The function 🔥 of good software is to make the complex appear simple.” – Grady Booch",
    "“Talk is cheap. Show me the code.” – 👩‍💻 Linus Torvalds",
    "“Simplicity is the soul of 🚀 efficiency.” – Austin Freeman",
    "“Programs must 👨‍💻 be written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“First, solve the problem. Then, 👩‍💻 write the code.” – John Johnson",
    "“Programs must be written for people to read, and 💻 only incidentally for machines to execute.” – Harold Abelson",
    "“First, solve the problem. Then, 🔍 write the code.” – John Johnson",
    "“Simplicity is the soul of efficiency.” – 👩‍💻 Austin Freeman",
    "“Software is a great combination of artistry and 📊 engineering.” – Bill Gates",
    "“Any fool can write code that a computer can understand. 🔧 Good programmers write code that humans can understand.” – Martin Fowler",
    "“Programs must be written for people to read, and only incidentally for ✨ machines to execute.” – Harold Abelson",
    "“First, solve the problem. Then, 👨‍💻 write the code.” – John Johnson",
    "“Simplicity is the soul of efficiency.” – 👩‍💻 Austin Freeman",
    "“Simplicity is 🔍 the soul of efficiency.” – Austin Freeman",
    "“Simplicity is 👨‍💻 the soul of efficiency.” – Austin Freeman",
    "“Talk is 📊 cheap. Show me the code.” – Linus Torvalds",
    "“Simplicity is the soul of 📘 efficiency.” – Austin Freeman",
    "“First, solve the problem. 🔥 Then, write the code.” – John Johnson",
    "“Any fool can write code that 🤖 a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 🔧 John Johnson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can 🚀 understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the ✨ code.” – John Johnson",
    "“Any fool can write code that a computer can understand. Good programmers write code 👩‍💻 that humans can understand.” – Martin Fowler",
    "“First, solve 🔥 the problem. Then, write the code.” – John Johnson",
    "“Any fool can write code that a computer 🖥️ can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Simplicity is the 🔍 soul of efficiency.” – Austin Freeman",
    "“Talk is cheap. 🖥️ Show me the code.” – Linus Torvalds",
    "“Simplicity is the soul of efficiency.” – 👨‍💻 Austin Freeman",
    "“The function of good software is to make the complex appear simple.” – 📘 Grady Booch",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can 🔥 understand.” – Martin Fowler",
    "“Simplicity is the soul of 💻 efficiency.” – Austin Freeman",
    "“Simplicity is the soul of efficiency.” – 👩‍💻 Austin Freeman",
    "“Simplicity is the soul 🖥️ of efficiency.” – Austin Freeman",
    "“Programs must be written for 🔥 people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Any fool can write code that 👨‍💻 a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 💻 John Johnson",
    "“First, solve the problem. Then, 🚀 write the code.” – John Johnson",
    "“Talk is 👨‍💻 cheap. Show me the code.” – Linus Torvalds",
    "“First, solve the problem. Then, 🧠 write the code.” – John Johnson",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 🔥 Harold Abelson",
    "“Talk is cheap. Show me the code.” – 🤖 Linus Torvalds",
    "“Simplicity is 💻 the soul of efficiency.” – Austin Freeman",
    "“Simplicity is the soul of efficiency.” – ✨ Austin Freeman",
    "“Programs must be 🚀 written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“The function of good software is to make the 👩‍💻 complex appear simple.” – Grady Booch",
    "“Programs must be written for people to read, and only incidentally for machines to 🖥️ execute.” – Harold Abelson",
    "“The function of good software is to make the complex appear simple.” – 📘 Grady Booch",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 👩‍💻 Martin Fowler",
    "“Software is a great combination 🖥️ of artistry and engineering.” – Bill Gates",
    "“Any fool can write code that a computer can understand. Good programmers write 📘 code that humans can understand.” – Martin Fowler",
    "“The function of good software is to make the 🔧 complex appear simple.” – Grady Booch",
    "“Talk is cheap. Show me the code.” – 👨‍💻 Linus Torvalds",
    "“First, solve the problem. Then, write the code.” – 💻 John Johnson",
    "“The function of good software is to 🖥️ make the complex appear simple.” – Grady Booch",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 🤖 Harold Abelson",
    "“Simplicity is 📘 the soul of efficiency.” – Austin Freeman",
    "“Programs must be written for people to read, and only incidentally for machines to 🔍 execute.” – Harold Abelson",
    "“Talk is cheap. Show me 👨‍💻 the code.” – Linus Torvalds",
    "“Software is a 🚀 great combination of artistry and engineering.” – Bill Gates",
    "“The function of good software is to make the complex 🔥 appear simple.” – Grady Booch",
    "“Simplicity is the soul of efficiency.” – 🚀 Austin Freeman",
    "“Simplicity is the soul of efficiency.” – 📘 Austin Freeman",
    "“First, solve the problem. Then, write the 🧠 code.” – John Johnson",
    "“Software is a great combination of ✨ artistry and engineering.” – Bill Gates",
    "“Programs must be 🤖 written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Simplicity is the soul of efficiency.” – 🚀 Austin Freeman",
    "“Software is ✨ a great combination of artistry and engineering.” – Bill Gates",
    "“Programs must be written for 📊 people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“The function of good software is to make the complex appear simple.” – 🚀 Grady Booch",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 🔧 Martin Fowler",
    "“Software is a great combination of 🤖 artistry and engineering.” – Bill Gates",
    "“Simplicity is the soul of ✨ efficiency.” – Austin Freeman",
    "“Programs must be written for people to read, and only incidentally for machines to 📊 execute.” – Harold Abelson",
    "“Talk is cheap. Show me the code.” – ✨ Linus Torvalds",
    "“Talk is cheap. Show me the code.” – 🚀 Linus Torvalds",
    "“Simplicity is 🤖 the soul of efficiency.” – Austin Freeman",
    "“Talk is cheap. Show me the code.” – 🖥️ Linus Torvalds",
    "“Software is 🤖 a great combination of artistry and engineering.” – Bill Gates",
    "“Simplicity is 👨‍💻 the soul of efficiency.” – Austin Freeman",
    "“Simplicity is the 👩‍💻 soul of efficiency.” – Austin Freeman",
    "“Software is a great combination of 🖥️ artistry and engineering.” – Bill Gates",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 📘 Harold Abelson",
    "“Simplicity is the soul of efficiency.” – 🔍 Austin Freeman",
    "“Simplicity is the 🔧 soul of efficiency.” – Austin Freeman",
    "“The function of good software is to make the complex appear 🔧 simple.” – Grady Booch",
    "“Simplicity is the soul of efficiency.” – 🖥️ Austin Freeman",
    "“Talk is cheap. Show me the code.” – 👩‍💻 Linus Torvalds",
    "“Talk is cheap. Show me the 🔧 code.” – Linus Torvalds",
    "“The function 👨‍💻 of good software is to make the complex appear simple.” – Grady Booch",
    "“Programs must be written for 🔥 people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“The function of 👨‍💻 good software is to make the complex appear simple.” – Grady Booch",
    "“Talk is 📘 cheap. Show me the code.” – Linus Torvalds",
    "“Talk is cheap. Show me the 🧠 code.” – Linus Torvalds",
    "“Software is a great combination of artistry and 🚀 engineering.” – Bill Gates",
    "“Programs must be written for people to read, and only 📘 incidentally for machines to execute.” – Harold Abelson",
    "“The function of 🤖 good software is to make the complex appear simple.” – Grady Booch",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 📊 Harold Abelson",
    "“Talk is cheap. Show me the code.” – 💻 Linus Torvalds",
    "“Programs must be written for people to read, and 🔥 only incidentally for machines to execute.” – Harold Abelson",
    "“Any fool can write code that a computer 👨‍💻 can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 🧠 John Johnson",
    "“Simplicity is the soul ✨ of efficiency.” – Austin Freeman",
    "“The function of good ✨ software is to make the complex appear simple.” – Grady Booch",
    "“Software is a great combination of artistry and engineering.” – 👩‍💻 Bill Gates",
    "“First, solve the problem. 📘 Then, write the code.” – John Johnson",
    "“Simplicity is the soul of 🖥️ efficiency.” – Austin Freeman",
    "“First, solve the 🧠 problem. Then, write the code.” – John Johnson",
    "“First, solve the problem. Then, write the 👩‍💻 code.” – John Johnson",
    "“First, solve the problem. Then, write the code.” – 📘 John Johnson",
    "“Software is a great combination of artistry ✨ and engineering.” – Bill Gates",
    "“Talk is 🖥️ cheap. Show me the code.” – Linus Torvalds",
    "“Talk is cheap. Show me the code.” – 📘 Linus Torvalds",
    "“Programs must be written for people 🔍 to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Software is 📘 a great combination of artistry and engineering.” – Bill Gates",
    "“First, solve the problem. Then, write the code.” – 📊 John Johnson",
    "“The function of good software is to make the complex appear simple.” – 💻 Grady Booch",
    "“Any fool can write code that a computer can 🖥️ understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Any fool can write 🔍 code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Talk is 🚀 cheap. Show me the code.” – Linus Torvalds",
    "“The function of good software is to make 👩‍💻 the complex appear simple.” – Grady Booch",
    "“First, solve the problem. Then, write 🔧 the code.” – John Johnson",
    "“Software is 🖥️ a great combination of artistry and engineering.” – Bill Gates",
    "“Any fool can write code that a computer can understand. Good programmers write 🔧 code that humans can understand.” – Martin Fowler",
    "“Software is a great combination of artistry and 💻 engineering.” – Bill Gates",
    "“The function of good software is 👩‍💻 to make the complex appear simple.” – Grady Booch",
    "“Talk is cheap. Show 📘 me the code.” – Linus Torvalds",
    "“Simplicity is the soul of 🔧 efficiency.” – Austin Freeman",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 📊 Martin Fowler",
    "“Software is a 🔥 great combination of artistry and engineering.” – Bill Gates",
    "“Talk is cheap. Show me the code.” – 🧠 Linus Torvalds",
    "“First, solve the problem. Then, write the 🔧 code.” – John Johnson",
    "“Software is a great combination of artistry and engineering.” – 🔧 Bill Gates",
    "“Simplicity is the soul of 🔥 efficiency.” – Austin Freeman",
    "“The function of good software is to make the complex ✨ appear simple.” – Grady Booch",
    "“First, solve the ✨ problem. Then, write the code.” – John Johnson",
    "“The function of good software is 👩‍💻 to make the complex appear simple.” – Grady Booch",
    "“First, solve the 👨‍💻 problem. Then, write the code.” – John Johnson",
    "“The function of good software 🖥️ is to make the complex appear simple.” – Grady Booch",
    "“Any fool can write 👨‍💻 code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Simplicity is the soul 🚀 of efficiency.” – Austin Freeman",
    "“Simplicity is the 👩‍💻 soul of efficiency.” – Austin Freeman",
    "“First, solve the problem. Then, write the code.” – 🔥 John Johnson",
    "“Simplicity is the soul of efficiency.” – ✨ Austin Freeman",
    "“Software is a great combination of artistry and 👩‍💻 engineering.” – Bill Gates",
    "“Any fool can write code 🤖 that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Software is a great combination 👨‍💻 of artistry and engineering.” – Bill Gates",
    "“First, solve the problem. Then, write the 👨‍💻 code.” – John Johnson",
    "“Programs must be written 🧠 for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 🖥️ Martin Fowler",
    "“Talk is cheap. Show me the code.” – 👨‍💻 Linus Torvalds",
    "“The function of good software is 🔍 to make the complex appear simple.” – Grady Booch",
    "“Software is a great combination of artistry and ✨ engineering.” – Bill Gates",
    "“Simplicity is the soul of ✨ efficiency.” – Austin Freeman",
    "“Software is a great combination of 📘 artistry and engineering.” – Bill Gates",
    "“The function of 🔧 good software is to make the complex appear simple.” – Grady Booch",
    "“Simplicity is the 💻 soul of efficiency.” – Austin Freeman",
    "“Simplicity is 🔥 the soul of efficiency.” – Austin Freeman",
    "“Software is a great combination of artistry and 🔍 engineering.” – Bill Gates",
    "“Programs must be written for people to read, and only incidentally 🤖 for machines to execute.” – Harold Abelson",
    "“Any fool can write 💻 code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“The function of good software is 📘 to make the complex appear simple.” – Grady Booch",
    "“First, solve the problem. Then, write 🖥️ the code.” – John Johnson",
    "“Software is a great combination 📊 of artistry and engineering.” – Bill Gates",
    "“Software is a great combination of ✨ artistry and engineering.” – Bill Gates",
    "“Any fool can write code that a 🔍 computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“The function of good software is 🚀 to make the complex appear simple.” – Grady Booch",
    "“Simplicity is the soul of efficiency.” – 🚀 Austin Freeman",
    "“First, solve the 🖥️ problem. Then, write the code.” – John Johnson",
    "“The function of good software is to make the complex appear simple.” – 🖥️ Grady Booch",
    "“Any fool can write 👩‍💻 code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Simplicity is the soul of efficiency.” – 🔍 Austin Freeman",
    "“Talk is cheap. Show me the code.” – 📘 Linus Torvalds",
    "“Simplicity is the ✨ soul of efficiency.” – Austin Freeman",
    "“The function of good software is to make ✨ the complex appear simple.” – Grady Booch",
    "“The function of good software is to make the complex 🔥 appear simple.” – Grady Booch",
    "“Software is a great combination 🔍 of artistry and engineering.” – Bill Gates",
    "“Talk is cheap. Show 👩‍💻 me the code.” – Linus Torvalds",
    "“The function of good software is to 🔍 make the complex appear simple.” – Grady Booch",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – ✨ Martin Fowler",
    "“The function of good software is to make the complex appear 🔥 simple.” – Grady Booch",
    "“First, solve the problem. Then, write the 🤖 code.” – John Johnson",
    "“First, solve 📊 the problem. Then, write the code.” – John Johnson",
    "“Simplicity is 👨‍💻 the soul of efficiency.” – Austin Freeman",
    "“Programs must be written for people to read, and only incidentally for machines to 🤖 execute.” – Harold Abelson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans 💻 can understand.” – Martin Fowler",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 🖥️ Harold Abelson",
    "“First, solve the problem. 🚀 Then, write the code.” – John Johnson",
    "“Programs must be written for people to read, 📘 and only incidentally for machines to execute.” – Harold Abelson",
    "“First, solve the problem. Then, ✨ write the code.” – John Johnson",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 📊 Harold Abelson",
    "“The function of good 🚀 software is to make the complex appear simple.” – Grady Booch",
    "“First, solve the problem. Then, write the code.” – ✨ John Johnson",
    "“Programs must be written ✨ for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Software is a great combination of artistry and engineering.” – 🚀 Bill Gates",
    "“Programs must be written for people to ✨ read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Programs must be written 💻 for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Talk is cheap. Show me the code.” – 🔥 Linus Torvalds",
    "“Simplicity is the soul of efficiency.” – 📊 Austin Freeman",
    "“Any fool can write code that a computer can understand. Good programmers write 🤖 code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, 📊 write the code.” – John Johnson",
    "“Talk is cheap. Show me the code.” – 📘 Linus Torvalds",
    "“First, solve the problem. Then, write the 📘 code.” – John Johnson",
    "“Software is a great combination of 🤖 artistry and engineering.” – Bill Gates",
    "“Talk is cheap. Show me 🔍 the code.” – Linus Torvalds",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 🖥️ Martin Fowler",
    "“Programs must 📊 be written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“The function of good software is to 🚀 make the complex appear simple.” – Grady Booch",
    "“The function of good software 🔍 is to make the complex appear simple.” – Grady Booch",
    "“Programs must be written for people to read, and only ✨ incidentally for machines to execute.” – Harold Abelson",
    "“Any fool can write code that a computer ✨ can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, ✨ write the code.” – John Johnson",
    "“The function of good software is to make the complex appear simple.” – 🧠 Grady Booch",
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – 📘 Harold Abelson",
    "“The function of good software is to 👩‍💻 make the complex appear simple.” – Grady Booch",
    "“Software is a great 🖥️ combination of artistry and engineering.” – Bill Gates",
    "“The function of good software is 🚀 to make the complex appear simple.” – Grady Booch",
    "“The function of good software is to make 🔧 the complex appear simple.” – Grady Booch",
    "“Any fool can write 📘 code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“Programs must be written for people 👩‍💻 to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – 📘 Martin Fowler",
    "“First, solve the 🚀 problem. Then, write the code.” – John Johnson",
    "“Software is 📘 a great combination of artistry and engineering.” – Bill Gates",
    "“Any fool can write code that a computer can understand. Good programmers 📘 write code that humans can understand.” – Martin Fowler",
    "“Talk is cheap. Show me the code.” – 🔍 Linus Torvalds",
    "“Software is 📘 a great combination of artistry and engineering.” – Bill Gates",
    "“Programs must be written for people to 🚀 read, and only incidentally for machines to execute.” – Harold Abelson",
    "“The function of good software is to make the complex appear simple.” – 📘 Grady Booch",
    "“Software is a great combination 👨‍💻 of artistry and engineering.” – Bill Gates",
    "“Software is a 🔍 great combination of artistry and engineering.” – Bill Gates",
    "“Simplicity is the soul of efficiency.” – 🔍 Austin Freeman",
    "“The function of good software is 🔍 to make the complex appear simple.” – Grady Booch",
    "“First, solve 📘 the problem. Then, write the code.” – John Johnson",
    "“Simplicity is the 🔥 soul of efficiency.” – Austin Freeman",
    "“Talk is cheap. Show me 🤖 the code.” – Linus Torvalds",
    "“Talk is cheap. Show me the code.” – 📊 Linus Torvalds",
    "“The function of good software 🚀 is to make the complex appear simple.” – Grady Booch",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans 🤖 can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – 🚀 John Johnson",
    "“Programs must 🔧 be written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Talk is cheap. Show me the code.” – 🤖 Linus Torvalds",
    "“The function of good software is to make the complex appear ✨ simple.” – Grady Booch",
    "“Programs must be written for people to read, and 🔧 only incidentally for machines to execute.” – Harold Abelson"
]

@bot.message_handler(commands=['start'])
def start(message):
    bot.send_message(message.chat.id, "👋 Welcome! Send /quote to get a random Computer Science quote.")

@bot.message_handler(commands=['quote'])
def send_quote(message):
    quote = random.choice(cs_quotes)
    bot.send_message(message.chat.id, f"💡 {quote}")

bot.polling()
